name: CI Pipeline

# Workflow wird bei einem Push oder Pull Request auf den main-Branch ausgeführt
on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  test:
    runs-on: ubuntu-latest

    # Installations- und Testschritte
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'  # Version von Node.js (anpassbar)

      - name: Install dependencies
        run: npm install

      - name: Run Jest tests
        run: npm run test   # Standardmäßig Jest-Tests

      - name: Install Cypress
        run: npm install cypress --save-dev

      - name: Run Cypress tests
        run: npm run cypress:run
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }} # Falls Cypress Dashboard genutzt wird

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build the Next.js project
        run: npm run build
